### PR TITLE
Add parameters to checkout action

### PR DESCRIPTION
**Pull request by robertodr**
- Fetch all branches and tags.
- Use LFS. This is helpful when using notebook content, which might get a bit large.

### CODE REVIEW

**Comment by bast** [comment]
So the `fetch-depth: 0` does what `git fetch` did?

**Comment by rkdarst** [comment]
Seems to be: https://github.com/actions/checkout

Would be nice to fetch depth=1 for all branches and tags, but they don't seem to support that in the action.  So I guess github doesn't care that much...

thanks!

**Comment by robertodr** [comment]
Why are all branches and tags needed?

**Comment by bast** [comment]
I think this is so that we potentially can build all branches so that we can serve also work in progress branches and not only the one production branch. If I understood the question and the setup correctly.

**Pull request merged**
